# 목적 
# 
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:glb|gltf|bin|png|jpe?g|webp|ktx2|js|css|woff2?)$ {
        try_files $uri =404;
        # 캐싱시간
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    gzip on;
    gzip_types text/css application/javascript application/json model/gltf+json;
}

